import * as Notifications from 'expo-notifications';

export class LocalNotificationService {
  // Enviar notificación local inmediata
  static async showLocalNotification(title: string, body: string, data?: any) {
    try {
      await Notifications.scheduleNotificationAsync({
        content: {
          title: title,
          body: body,
          sound: true,
          data: data || {},
        },
        trigger: {
          type: Notifications.SchedulableTriggerInputTypes.TIME_INTERVAL,
          seconds: 1,
        },
      });
      console.log('✅ Notificación local programada');
    } catch (error) {
      console.error('❌ Error mostrando notificación local:', error);
    }
  }

  // Simular recepción de mensaje
  static async simulateMessageReceived(message: string, senderName: string, chatId?: string) {
    await this.showLocalNotification(
      `💬 Nuevo mensaje de ${senderName}`,
      message.length > 50 ? message.substring(0, 50) + '...' : message,
      {
        chatId,
        type: 'new_message', 
        senderName,
        timestamp: new Date().toISOString()
      }
    );
  }

  // 🆕 NOTIFICACIONES DE EMERGENCIA/INFO
  static async showEmergencyNotification(title: string, message: string, chatId?: string) {
    await this.showLocalNotification(
      title,
      message,
      {
        chatId,
        type: 'emergency_info',
        timestamp: new Date().toISOString()
      }
    );
  }

  // 🆕 Simular conversación automática para testing
  static async simulateAutoReply(displayName: string, chatId?: string) {
    const respuestas = [
      '¡Hola! ¿Cómo estás?',
      'Gracias por tu mensaje 💖',
      'Estoy bien, ¿y tú?',
      '¿Podemos hablar más tarde?',
      '¡Claro! Me parece bien 👍',
      '¿A qué hora quedamos?',
      'Te extrañaba 😊',
      '¿Viste las últimas noticias?',
      '¡Feliz día! 🌟',
      '¿Necesitas ayuda con algo?'
    ];
    
    const respuestaAleatoria = respuestas[Math.floor(Math.random() * respuestas.length)];
    
    // Notificación de respuesta simulada
    setTimeout(async () => {
      await this.showLocalNotification(
        `💬 ${displayName}`,
        respuestaAleatoria,
        { 
          chatId, 
          type: 'simulated_reply',
          autoGenerated: true 
        }
      );
    }, 3000);

    return respuestaAleatoria;
  }
}