import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export const getStyles = (isDarkMode: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: isDarkMode ? '#121212' : '#FFF5F8',
  },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  scrollViewContent: {
    padding: 20,
    paddingBottom: 40,
  },
  section: {
    marginVertical: 8,
    padding: 16,
    borderRadius: 8,
    backgroundColor: isDarkMode ? '#1E1E1E' : '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 16,
    color: isDarkMode ? Colors.dark.text : Colors.light.text,
  },
  input: {
    width: '100%',
    height: 50,
    borderWidth: 1,
    borderColor: isDarkMode ? '#555' : '#E8EAF6',
    borderRadius: 10,
    paddingHorizontal: 15,
    marginBottom: 15,
    color: isDarkMode ? '#FFFFFF' : '#333333',
    backgroundColor: isDarkMode ? '#2a2a2a' : '#F5F5F5',
  },
  inputButton: {
    backgroundColor: isDarkMode ? '#3D3147' : '#FFF5F8',
    borderWidth: 1,
    borderColor: isDarkMode ? '#6B5B62' : '#FFE4ED',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  inputText: {
    color: isDarkMode ? '#FFFFFF' : '#333333',
    fontSize: 16,
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
    paddingTop: 15,
  },
  button: {
    backgroundColor: isDarkMode ? '#BB86FC' : '#5C6BC0',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: 15,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  listItem: {
    backgroundColor: isDarkMode ? '#2a2a2a' : '#F5F5F5',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: isDarkMode ? '#444' : '#E0E0E0',
  },
  logText: {
    fontSize: 14,
    color: isDarkMode ? '#E0E0E0' : '#424242',
  },
  logTextBold: {
    fontSize: 16,
    fontWeight: 'bold',
    color: isDarkMode ? '#FFFFFF' : '#212121',
  },
  inputLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: isDarkMode ? '#FFB6D9' : '#C62368',
  },
   notesContainer: {
    marginBottom: 20,
  },

  saveButton: {
    backgroundColor: isDarkMode ? '#B794F6' : '#FF6B9D',
    padding: 16,
    borderRadius: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 6,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  listSection: {
    marginTop: 8,
  },
  listTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 16,
    color: isDarkMode ? '#FFB6D9' : '#C62368',
    paddingHorizontal: 4,
  },
  appointmentCard: {
    backgroundColor: isDarkMode ? '#2A2335' : '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    shadowColor: isDarkMode ? '#000' : '#D6336C',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: isDarkMode ? '#3D3147' : '#FFE4ED',
  },
  appointmentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  appointmentDateBadge: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: isDarkMode ? '#3D3147' : '#FFE4ED',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
   appointmentDateIcon: {
    fontSize: 24,
  },
  appointmentInfo: {
    flex: 1,
  },
  appointmentDate: {
    fontSize: 16,
    fontWeight: '700',
    color: isDarkMode ? '#FFB6D9' : '#C62368',
    marginBottom: 4,
  },
  appointmentTime: {
    fontSize: 14,
    color: isDarkMode ? '#D4A5C0' : '#9E7B8E',
    fontWeight: '500',
  },
  appointmentNotes: {
    fontSize: 14,
    lineHeight: 20,
    color: isDarkMode ? '#D4A5C0' : '#6B5B62',
  },
  emptyStateCard: {
    backgroundColor: isDarkMode ? '#2A2335' : '#FFFFFF',
    borderRadius: 20,
    padding: 40,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: isDarkMode ? '#3D3147' : '#FFE4ED',
  },
  emptyStateIcon: {
    fontSize: 48,
    marginBottom: 16,
  },
  emptyListText: {
    textAlign: 'center',
    marginTop: 20,
    color: isDarkMode ? '#aaa' : '#777',
  },
   emptyStateText: {
    fontSize: 15,
    textAlign: 'center',
    color: isDarkMode ? '#D4A5C0' : '#9E7B8E',
    lineHeight: 22,
  },
   emptyIcon: {
    fontSize: 64,
    marginBottom: 16,
  },
  emptyText: {
    fontSize: 16,
    textAlign: 'center',
    color: isDarkMode ? '#D4A5C0' : '#9E7B8E',
    lineHeight: 24,
  },
 loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: isDarkMode ? '#FFB6D9' : '#D6336C',
    fontWeight: '600',
  },
});
