import { StyleSheet } from 'react-native';

export const getHomeStyles = (isDarkMode: boolean) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: isDarkMode ? '#121212' : '#FFF5F8',
    },
    headerContainer: {
      paddingTop: 20,
      paddingHorizontal: 20,
      paddingBottom: 15,
      alignItems: 'center',
    },
    title: {
      fontSize: 28,
      fontWeight: '700',
      textAlign: 'center',
      color: isDarkMode ? '#FFB6D9' : '#D6336C',
      marginBottom: 8,
      letterSpacing: 0.5,
    },
    subtitle: {
      fontSize: 14,
      textAlign: 'center',
      color: isDarkMode ? '#D4A5C0' : '#9E7B8E',
      fontStyle: 'italic',
    },
    tipCard: {
      marginHorizontal: 20,
      marginTop: 20,
      marginBottom: 25,
      backgroundColor: isDarkMode ? '#2A2335' : '#FFFFFF',
      borderRadius: 24,
      padding: 24,
      shadowColor: isDarkMode ? '#000' : '#D6336C',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDarkMode ? 0.3 : 0.12,
      shadowRadius: 12,
      elevation: 6,
      borderWidth: 1,
      borderColor: isDarkMode ? '#3D3147' : '#FFE4ED',
      alignItems: 'center', 
      justifyContent: 'center',
    },
    tipIconContainer: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: isDarkMode ? '#3D3147' : '#FFE4ED',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 16,
    },
    tipIcon: {
      fontSize: 32,
    },
    tipTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: isDarkMode ? '#FFB6D9' : '#C62368',
      marginBottom: 12,
    },
    tipText: {
      fontSize: 15,
      lineHeight: 22,
      color: isDarkMode ? '#D4A5C0' : '#6B5B62',
    },
    premiumBanner: {
      marginHorizontal: 20,
      marginBottom: 25,
      backgroundColor: isDarkMode ? '#3D3147' : '#FFF0F5',
      borderRadius: 20,
      padding: 20,
      flexDirection: 'row',
      alignItems: 'center',
      shadowColor: isDarkMode ? '#000' : '#D6336C',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: isDarkMode ? 0.3 : 0.1,
      shadowRadius: 8,
      elevation: 4,
      borderWidth: 1.5,
      borderColor: isDarkMode ? '#6B5B62' : '#FFD4E5',
    },
    premiumIconBadge: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: isDarkMode ? '#B794F6' : '#FFD700',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 16,
    },
    premiumContent: {
      flex: 1,
    },
    premiumTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: isDarkMode ? '#FFB6D9' : '#C62368',
      marginBottom: 4,
    },
    premiumSubtitle: {
      fontSize: 13,
      color: isDarkMode ? '#D4A5C0' : '#9E7B8E',
      marginBottom: 8,
    },
    premiumButton: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
    },
    premiumButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: isDarkMode ? '#B794F6' : '#FF6B9D',
      marginRight: 4,
    },
    actionsGrid: {
      paddingHorizontal: 16,
    },
    actionRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 16,
    },
    actionCard: {
      width: '48%',
      aspectRatio: 1,
      borderRadius: 20,
      padding: 16,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
    },
    actionCardPink: {
      backgroundColor: isDarkMode ? '#2A2335' : '#FFE4ED',
      borderWidth: 1,
      borderColor: isDarkMode ? '#3D3147' : '#FFCCE0',
    },
    actionCardPurple: {
      backgroundColor: isDarkMode ? '#2A2335' : '#F3EBFF',
      borderWidth: 1,
      borderColor: isDarkMode ? '#3D3147' : '#E4D4FF',
    },
    actionCardCoral: {
      backgroundColor: isDarkMode ? '#2A2335' : '#FFE9E0',
      borderWidth: 1,
      borderColor: isDarkMode ? '#3D3147' : '#FFD4C4',
    },
    actionCardMint: {
      backgroundColor: isDarkMode ? '#2A2335' : '#E0FFF4',
      borderWidth: 1,
      borderColor: isDarkMode ? '#3D3147' : '#C4FFE9',
    },
    actionCardBlue: {
      backgroundColor: isDarkMode ? '#2A2335' : '#E3F2FD',
      borderWidth: 1,
      borderColor: isDarkMode ? '#3D3147' : '#BBDEFB',
    },
    actionCardRose: {
      backgroundColor: isDarkMode ? '#2A2335' : '#FCE4EC',
      borderWidth: 1,
      borderColor: isDarkMode ? '#3D3147' : '#F8BBD0',
    },
    actionIconContainer: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: isDarkMode ? 'rgba(255, 182, 217, 0.1)' : 'rgba(255, 255, 255, 0.9)',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 12,
    },
    actionTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: isDarkMode ? '#FFB6D9' : '#6B5B62',
      textAlign: 'center',
      marginTop: 4,
    },
    actionSubtitle: {
      fontSize: 13,
      color: isDarkMode ? '#D4A5C0' : '#9E7B8E',
      textAlign: 'center',
      marginTop: 2,
    },
    bottomSpacing: {
      height: 40,
    },
  });