import { StyleSheet } from 'react-native';

export const getProfileStyles = (theme: 'light' | 'dark') =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme === 'dark' ? '#121212' : '#FFF5F8',
    },
    loadingScreenContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme === 'dark' ? '#121212' : '#FFF5F8',
    },
    loadingScreenText: {
      marginTop: 16,
      fontSize: 16,
      color: theme === 'dark' ? '#FFB6D9' : '#D6336C',
      fontWeight: '600',
    },
    header: {
      padding: 20,
      paddingBottom: 10,
      alignItems: 'center',
    },
    title: {
      fontSize: 28,
      fontWeight: '700',
      color: theme === 'dark' ? '#FFB6D9' : '#D6336C',
      textAlign: 'center',
      marginBottom: 20,
      letterSpacing: 0.5,
    },
    subtitle: {
      fontSize: 14,
      textAlign: 'center',
      color: theme === 'dark' ? '#D4A5C0' : '#9E7B8E',
      fontStyle: 'italic',
    },
    profilePhotoSection: {
      alignItems: 'center',
      marginBottom: 30,
      marginTop: 10,
    },
    profilePhotoContainer: {
      position: 'relative',
      marginBottom: 12,
    },
    profilePhoto: {
      width: 130,
      height: 130,
      borderRadius: 65,
      borderWidth: 4,
      borderColor: theme === 'dark' ? '#B794F6' : '#FFB6D9',
    },
    changePhotoButton: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      backgroundColor: theme === 'dark' ? '#B794F6' : '#FFB6D9',
      width: 42,
      height: 42,
      borderRadius: 21,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 3,
      borderColor: theme === 'dark' ? '#121212' : '#FFF5F8',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    changePhotoText: {
      fontSize: 18,
    },
    photoPlaceholderText: {
      fontSize: 14,
      color: theme === 'dark' ? '#D4A5C0' : '#9E7B8E',
      textAlign: 'center',
      fontWeight: '500',
    },
    formSection: {backgroundColor: theme === 'dark' ? '#2A2335' : '#FFFFFF',
      marginHorizontal: 16,
      borderRadius: 20,
      paddingVertical: 8,
      shadowColor: theme === 'dark' ? '#000' : '#D6336C',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 4,
      paddingHorizontal: 20,
      
    },
    inputRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: theme === 'dark' ? '#3D3147' : '#FFE4ED',
    },
    label: {
      fontSize: 15,
      fontWeight: '500',
      color: theme === 'dark' ? '#FFB6D9' : '#C62368',
      width: '45%',
    },
    input: {
      flex: 1,
      textAlign: 'right',
      fontSize: 15,
      color: theme === 'dark' ? '#ddd' : '#6B5B62',
      padding: 8,
      fontWeight: '500',
    },
    dateButton: {
      flex: 1,
      alignItems: 'flex-end',
      paddingVertical: 8,
    },
    dateText: {
      fontSize: 15,
      color: theme === 'dark' ? '#ddd' : '#6B5B62',
      textAlign: 'right',
      fontWeight: '500',
    },
    disabledText: {
      color: theme === 'dark' ? '#666' : '#D4A5C0',
    },
    ageText: {
      fontSize: 15,
      color: theme === 'dark' ? '#ddd' : '#6B5B62',
      textAlign: 'right',
      flex: 1,
      fontWeight: '600',
    },
    // Styles for location manners
    modalOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
      width: '85%',
      maxHeight: '70%',
      backgroundColor: theme === 'dark' ? '#2A2335' : '#FFFFFF',
      borderRadius: 24,
      padding: 24,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 8,
      borderWidth: 1,
      borderColor: theme === 'dark' ? '#3D3147' : '#FFE4ED',
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '700',
      marginBottom: 20,
      textAlign: 'center',
      color: theme === 'dark' ? '#FFB6D9' : '#C62368',
    },
    locationList: {
      maxHeight: 400,
    },
    locationItem: {
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: theme === 'dark' ? '#333' : '#FFE4ED',
      borderRadius: 12,
      marginBottom: 4,
    },
    locationItemText: {
      fontSize: 16,
      color: theme === 'dark' ? '#fff' : '#000',
      fontWeight: '500',
    },
    selectedLocationText: {
      color: '#3b82f6',
      fontWeight: 'bold',
    },
    modalCloseButton: {
      marginTop: 20,
      padding: 14,
      backgroundColor: theme === 'dark' ? '#3b82f6' : '#1e40af',
      borderRadius: 16,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    modalCloseText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontWeight: '700',
    },
    loadingContainer: {
      padding: 40,
      alignItems: 'center',
    },
    loadingText: {
      marginTop: 12,
      textAlign: 'center',
      color: theme === 'dark' ? '#D4A5C0' : '#000',
    },
    divider: {
      height: 1,
      backgroundColor: theme === 'dark' ? '#3D3147' : '#FFE4ED',
      marginVertical: 24,
      marginHorizontal: 16,
    },
    helpSection: {
      marginTop: 8,
      paddingHorizontal: 20,
    },
    helpTitle: {
      fontSize: 22,
      fontWeight: '700',
      marginBottom: 16,
      textAlign: 'center',
      color: theme === 'dark' ? '#FFB6D9' : '#C62368',
    },
    helpButton: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: theme === 'dark' ? '#2A2335' : '#FFFFFF',
      paddingVertical: 16,
      paddingHorizontal: 16,
      borderRadius: 16,
      marginBottom: 12,
      shadowColor: theme === 'dark' ? '#000' : '#D6336C',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      borderWidth: 1,
      borderColor: theme === 'dark' ? '#3D3147' : '#FFE4ED',
    },
    helpText: {
      fontSize: 16,
      color: theme === 'dark' ? '#fff' : '#1f2937',
      fontWeight: '600',
    },
    contactEmail: {
      textAlign: 'center',
      color: theme === 'dark' ? '#D4A5C0' : '#9E7B8E',
      fontSize: 15,
      marginTop: 12,
      fontStyle: 'italic',
    },
    arrow: {
      fontSize: 18,
      color: theme === 'dark' ? '#888' : '#9ca3af',
      fontWeight: 'bold',
    },
    saveButton: {
      backgroundColor: theme === 'dark' ? '#B794F6' : '#FF6B9D',
      padding: 18,
      borderRadius: 20,
      marginHorizontal: 20,
      marginTop: 30,
      marginBottom: 12,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
      elevation: 6,
    },
    saveButtonText: {
      color: '#FFFFFF',
      fontSize: 17,
      fontWeight: '700',
      letterSpacing: 0.5,
    },
    logoutButton: {
      backgroundColor: theme === 'dark' ? '#3D3147' : '#FFE4ED',
      padding: 16,
      borderRadius: 20,
      marginHorizontal: 20,
      marginBottom: 30,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: theme === 'dark' ? '#6B5B62' : '#FFCCE0',
    },
    logoutButtonText: {
      color: theme === 'dark' ? '#FFB6D9' : '#C62368',
      fontSize: 16,
      fontWeight: '700',
    },
  });

// Estilos para la vista de perfil de usuario (cuando ves el perfil de otro usuario)
export const getUserProfileStyles = (isDarkMode: boolean) =>
  StyleSheet.create({
    centered: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    container: {
      flex: 1,
      backgroundColor: isDarkMode ? '#121212' : '#FFF5F8',
    },
    listContent: {
      paddingBottom: 20,
    },
    headerCard: {
      marginHorizontal: 20,
      marginTop: 20,
      marginBottom: 20,
      backgroundColor: isDarkMode ? '#2A2335' : '#FFFFFF',
      borderRadius: 24,
      padding: 24,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDarkMode ? 0.3 : 0.1,
      shadowRadius: 12,
      elevation: 6,
      borderWidth: 1,
      borderColor: isDarkMode ? '#3D3147' : '#FFE4ED',
    },
    avatar: {
      width: 120,
      height: 120,
      borderRadius: 60,
      borderWidth: 4,
      borderColor: isDarkMode ? '#B794F6' : '#FFB6D9',
      marginBottom: 16,
    },
    name: {
      fontSize: 24,
      fontWeight: '700',
      marginBottom: 8,
      textAlign: 'center',
      color: isDarkMode ? '#FFB6D9' : '#C62368',
    },
    location: {
      fontSize: 15,
      color: isDarkMode ? '#D4A5C0' : '#9E7B8E',
      marginBottom: 16,
      textAlign: 'center',
      lineHeight: 22,
    },
    inlineMessageButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isDarkMode ? '#B794F6' : '#FF6B9D',
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 20,
      marginTop: 8,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    inlineMessageButtonText: {
      color: '#FFFFFF',
      fontWeight: '700',
      fontSize: 15,
      letterSpacing: 0.5,
    },
    postsSection: {
      marginHorizontal: 20,
    },
    postsSectionTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: isDarkMode ? '#FFB6D9' : '#C62368',
      marginBottom: 16,
      marginLeft: 4,
    },
    postCard: {
      backgroundColor: isDarkMode ? '#2A2335' : '#FFFFFF',
      borderRadius: 20,
      padding: 20,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: isDarkMode ? '#3D3147' : '#FFE4ED',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDarkMode ? 0.2 : 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
    postText: {
      fontSize: 15,
      lineHeight: 22,
      color: isDarkMode ? '#D4A5C0' : '#6B5B62',
      marginBottom: 12,
    },
    postImage: {
      width: '100%',
      height: 200,
      borderRadius: 12,
      marginTop: 8,
      marginBottom: 12,
    },
    postActions: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: isDarkMode ? '#3D3147' : '#FFE4ED',
    },
    postAction: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    postActionText: {
      fontSize: 14,
      color: isDarkMode ? '#D4A5C0' : '#9E7B8E',
      fontWeight: '600',
    },
    emptyState: {
      backgroundColor: isDarkMode ? '#2A2335' : '#FFFFFF',
      borderRadius: 20,
      padding: 32,
      marginHorizontal: 20,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: isDarkMode ? '#3D3147' : '#FFE4ED',
    },
    emptyStateText: {
      fontSize: 16,
      textAlign: 'center',
      color: isDarkMode ? '#D4A5C0' : '#9E7B8E',
      lineHeight: 24,
    },
    loadingContainer: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0,0,0,0.5)',
    },
    loadingText: {
      marginTop: 12,
      fontSize: 15,
      color: '#FFFFFF',
      fontWeight: '600',
    },
  });
