import { Colors } from '@/constants/Colors';
import { StyleSheet } from 'react-native';

export const getStyles = (isDarkMode: boolean) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: isDarkMode ? '#121212' : '#FFF5F8',
  },
  centerContent: {
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  scrollViewContent: {
    padding: 16,
    paddingBottom: 32,
  },
  symptomCard: {
      backgroundColor: isDarkMode ? "#3D3147" : "#FFF5F8",
      borderRadius: 16,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: isDarkMode ? "#6B5B62" : "#FFE4ED",
    },
    symptomHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 12,
    },
  section: {
    marginVertical: 8,
    padding: 16,
    borderRadius: 8,
    backgroundColor: isDarkMode ? '#1E1E1E' : '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 16,
    color: isDarkMode ? Colors.dark.text : Colors.light.text,
  },
  weekBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    marginBottom: 20,
  },
  weekBannerEmoji: {
    fontSize: 32,
    marginHorizontal: 12,
  },
  weekBannerText: {
    fontSize: 28,
    fontWeight: '700',
    textAlign: 'center',
    color: isDarkMode ? '#FFB6D9' : '#C62368',
  },
  fetalImage: {
    width: '100%',
    height: 280,
    borderRadius: 16,
    marginBottom: 20,
    backgroundColor: isDarkMode ? '#2a2a2a' : '#F5F5F5',
    resizeMode: 'contain',
  },
  dueDateCard: {
    backgroundColor: isDarkMode ? '#3D3147' : '#FFE4ED',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: isDarkMode ? '#6B5B62' : '#FFCCE0',
  },
  dueDateLabel: {
    fontSize: 14,
    color: isDarkMode ? '#D4A5C0' : '#9E7B8E',
    marginBottom: 8,
    fontWeight: '600',
  },
  dueDateText: {
    fontSize: 18,
    fontWeight: '700',
    color: isDarkMode ? '#FFB6D9' : '#C62368',
    textAlign: 'center',
  },
  updateDateLink: {
    paddingVertical: 12,
    alignItems: 'center',
  },
  updateDateLinkText: {
    fontSize: 14,
    color: isDarkMode ? '#D4A5C0' : '#9E7B8E',
    textDecorationLine: 'underline',
  },
   emptyStateCard: {
      backgroundColor: isDarkMode ? "#3D3147" : "#FFF5F8",
      borderRadius: 20,
      padding: 32,
      alignItems: "center",
      marginBottom: 16,
      borderWidth: 1,
      borderColor: isDarkMode ? "#6B5B62" : "#FFE4ED",
    },
    emptyStateIcon: {
      fontSize: 48,
      marginBottom: 16,
    },
    emptyStateText: {
      fontSize: 15,
      textAlign: "center",
      color: isDarkMode ? "#D4A5C0" : "#9E7B8E",
      lineHeight: 22,
    },
    emptyStateTextSmall: {
      fontSize: 14,
      textAlign: "center",
      color: isDarkMode ? "#D4A5C0" : "#9E7B8E",
      lineHeight: 20,
    },
    sectionIconContainer: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: isDarkMode ? "#3D3147" : "#FFE4ED",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 16,
      alignSelf: "center",
    },
    sectionIcon: {
      fontSize: 28,
    },
  weekText: {
    textAlign: 'center',
    fontSize: 16,
    fontWeight: 'bold',
    color: isDarkMode ? Colors.dark.text : Colors.light.text,
  },
  symptomIcon: {
      fontSize: 24,
    },
    symptomDate: {
      fontSize: 13,
      color: isDarkMode ? "#D4A5C0" : "#9E7B8E",
      fontWeight: "500",
    },
    symptomText: {
      fontSize: 14,
      lineHeight: 20,
      color: isDarkMode ? "#D4A5C0" : "#6B5B62",
    },
  input: {
    width: '100%',
    height: 50,
    borderWidth: 1,
    borderColor: isDarkMode ? '#555' : '#E8EAF6',
    borderRadius: 10,
    paddingHorizontal: 15,
    marginBottom: 15,
    color: isDarkMode ? '#FFFFFF' : '#333333',
    backgroundColor: isDarkMode ? '#2a2a2a' : '#F5F5F5',
  },
  inputButton: {
    width: '100%',
    height: 50,
    borderWidth: 1,
    borderColor: isDarkMode ? '#555' : '#E8EAF6',
    borderRadius: 10,
    paddingHorizontal: 15,
    marginBottom: 15,
    backgroundColor: isDarkMode ? '#2a2a2a' : '#F5F5F5',
    justifyContent: 'center',
  },
  inputContainer: {
      marginBottom: 16,
    },
    inputLabel: {
      fontSize: 15,
      fontWeight: "600",
      color: isDarkMode ? "#FFB6D9" : "#C62368",
      marginBottom: 8,
    },
  inputText: {
    color: isDarkMode ? '#FFFFFF' : '#333333',
    fontSize: 16,
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
    paddingTop: 15,
  },
  button: {
    backgroundColor: isDarkMode ? '#BB86FC' : '#5C6BC0',
    padding: 15,
    borderRadius: 10,
    alignItems: 'center',
    marginBottom: 15,
  },
  primaryButton: {
      backgroundColor: isDarkMode ? "#B794F6" : "#FF6B9D",
      padding: 16,
      borderRadius: 20,
      alignItems: "center",
      marginBottom: 8,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
      elevation: 6,
    },
    primaryButtonText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "700",
      letterSpacing: 0.5,
    },
  secondaryButton: {
    backgroundColor: isDarkMode ? "#3D3147" : "#FFE4ED",
    padding: 14,
    borderRadius: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: isDarkMode ? "#6B5B62" : "#FFCCE0",
  },
  secondaryButtonText: {
    color: isDarkMode ? "#FFB6D9" : "#C62368",
    fontSize: 15,
    fontWeight: "600",
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  listTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 15,
    marginBottom: 10,
    color: isDarkMode ? Colors.dark.text : Colors.light.text,
  },
  vitalsCard: {
      backgroundColor: isDarkMode ? "#3D3147" : "#FFF5F8",
      borderRadius: 16,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: isDarkMode ? "#6B5B62" : "#FFE4ED",
    },
    vitalsHeader: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 12,
    },
    vitalsBadge: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: isDarkMode ? "#6B5B62" : "#FFE4ED",
      justifyContent: "center",
      alignItems: "center",
      marginRight: 12,
    },
    vitalsBadgeIcon: {
      fontSize: 20,
    },
    vitalsInfo: {
      flex: 1,
    },
    vitalsValue: {
      fontSize: 18,
      fontWeight: "700",
      color: isDarkMode ? "#FFB6D9" : "#C62368",
      marginBottom: 4,
    },
    vitalsDate: {
      fontSize: 13,
      color: isDarkMode ? "#D4A5C0" : "#9E7B8E",
    },
    vitalsRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: isDarkMode ? "#6B5B62" : "#FFE4ED",
    },
    vitalsLabel: {
      fontSize: 14,
      color: isDarkMode ? "#D4A5C0" : "#9E7B8E",
      fontWeight: "600",
    },
    vitalsValueSmall: {
      fontSize: 15,
      fontWeight: "600",
      color: isDarkMode ? "#FFB6D9" : "#C62368",
    },
  listItem: {
    backgroundColor: isDarkMode ? '#2a2a2a' : '#F5F5F5',
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: isDarkMode ? '#444' : '#E0E0E0',
  },
  logText: {
    fontSize: 14,
    color: isDarkMode ? '#E0E0E0' : '#424242',
  },
  logTextDate: {
    fontSize: 12,
    color: isDarkMode ? '#aaa' : '#777',
    marginTop: 4,
  },
  logTextBold: {
    fontSize: 16,
    fontWeight: 'bold',
    color: isDarkMode ? '#FFFFFF' : '#212121',
  },
  emptyListText: {
    textAlign: 'center',
    marginTop: 20,
    color: isDarkMode ? '#aaa' : '#777',
  },
  emptyIcon: {
      fontSize: 64,
      marginBottom: 16,
  },
    emptyText: {
    fontSize: 16,
    textAlign: "center",
    color: isDarkMode ? "#D4A5C0" : "#9E7B8E",
    lineHeight: 24,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: isDarkMode ? "#FFB6D9" : "#D6336C",
    fontWeight: "600",
  },
});
